Try short sha (untested)
mbg/uow-apis pull request #24
Opened 2020-10-20 19:10 UTC by lol768

2020-10-20 19:45 UTC, mbg requested changes

2020-10-20 19:45 UTC, mbg commented on .github/workflows/haskell.yml
> +       echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})
Could you incorporate this into one the existing steps, so this doesn't need its own step? (Or at least bring the step name in line with the others?)

2020-10-20 19:45 UTC, mbg commented on .github/workflows/haskell.yml
> -
What has this line done to you!

2020-10-20 19:45 UTC, mbg commented on .github/workflows/haskell.yml
> +        release_name: Release $SHORTSHA
I don't think this needs to be an environment variable, just
```yaml
release_name: Release ${{ steps.vars.outputs.sha_short }}
```
should work, I think.

2020-10-20 20:18 UTC, lol768 commented on .github/workflows/haskell.yml
> -
jeez you like your breathing room much :P

2020-10-20 20:18 UTC, lol768 commented
mfw you introduce conflicts

2020-10-20 20:26 UTC, mbg commented on .github/workflows/haskell.yml
> -
What did _this_ line do to you!

2020-10-20 20:29 UTC, lol768 commented on .github/workflows/haskell.yml
> -
```suggestion

```

2020-10-20 20:58 UTC, mbg submitted a review, later dismissed

2020-10-20 20:58 UTC, mbg commented
Rebase pls

2020-10-23 10:38 UTC, mbg commented on .github/workflows/haskell.yml
> +        prerelease: false
As discussed on Slack, I modified the workflow quite a bit since you opened the PR. I'd still be happy to merge this if you changes these lines since they related to the previous action that was used here.
```suggestion
      with:
        name: Release ${{ steps.build.outputs.sha_short }}
```
See https://github.com/release-drafter/release-drafter#action-inputs

2020-10-23 11:56 UTC, merged